[unstable]
build-std = ["core"]

[build]
target = "xtensa-esp32-none-elf"
rustflags = [
  # GNU LD
  "-C", "link-arg=-Wl,-Tlinkall.x",
  "-C", "link-arg=-nostartfiles",

  # LLD
  # "-C", "link-arg=-Tlinkall.x",
  # "-C", "linker=rust-lld",
]

[env]
ESP_LOG="info"

[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor"
